//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace CarRental.Data
{
    public class Role
    {
        public int Id { get; set; }
        public UserRole Name { get; set; }

        public virtual ICollection<AuthInfo> AuthInfo { get; set; }

        public Role()
        {
            AuthInfo = new HashSet<AuthInfo>();
        }
    }
}
